#!/usr/bin/env bash

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Usage: ex <file>
ex ()
{
  if [ -f "$1" ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;; 
	  *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# useage: mkcd <directory>
mkcd ()
{
	[ ! -z $1 ] && mkdir $1 && cd $1 || echo "'$1' cannot be made"
}

# sudo not required for some system commands.
for command in mount umount pacman nmtui su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
    df="df -h" \
    free="free -m" \
    jctl="journalctl -p 3 -xb" \

# Colorize commands when possible.
alias \
	ls="ls -hFN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ip="ip -color=auto" \
    yay="yay --color=auto" \
    pacman="pacman --color=auto"

alias \
	la="ls -A" \
	ll="ls -l" \
	lal="ls -lA" \
    cmatrix="cmatrix -a -u 3" \
    xclip="xclip -selection clipboard" \
	yarn="yarn --use-yarnrc ${XDG_CONFIG_HOME:-$HOME/.config}/yarn/config" \
	sxiv="nsxiv" \
	py="python" \
    maven="mvn" \
    gradle.bat="gradle" \
    gradlew="gradle" \
    gradlew.bat="gradle" \
    speedtest.net="speedtest" \
    mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist" \
    mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist" \
    mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist" \
    mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist" \
    cleanup="sudo pacman -Rncs $(pacman -Qtdq)" \
    gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify" \
    gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys" \
    myip="curl ifconfig.co" \
    rr="curl -s -L http://bit.ly/10hA8iC | bash" \
    weather="curl wttr.in" 

# Github Aliases
 alias \
    addup="git add -u" \
    addall="git add ." \
    branch="git branch" \
    checkout="git checkout" \
    clone="git clone" \
    commit="git commit" \
	diff="git diff" \
    fetch="git fetch" \
    pull="git pull origin" \
    push="git push" \
    status="git status" \
    tag="git tag" \
    newtag="git tag -a" \
    config="git --git-dir=$HOME/Desktop/coding-stuff/github/matthew55/dotfiles/ --work-tree=$HOME"

# My many programing directories.
alias \
	coding="cd ~/Desktop/coding-stuff" \
	codingb="cd ~/Desktop/coding-stuff/bash" \
	codingc="cd ~/Desktop/coding-stuff/c" \
	codingcp="cd ~/Desktop/coding-stuff/c++" \
	codingcs="cd ~/Desktop/coding-stuff/c#" \
	codingj="cd ~/Desktop/coding-stuff/java" \
	codingjs="cd ~/Desktop/coding-stuff/javascript" \
	codingp="cd ~/Desktop/coding-stuff/python"\
	codingr="cd ~/Desktop/coding-stuff/ruby"\
	codingg="cd ~/Desktop/coding-stuff/github" \
	codinggc="cd ~/Desktop/coding-stuff/github/clones" \
	codinggcc="cd ~/Desktop/coding-stuff/github/clones/c" \
	codinggcj="cd ~/Desktop/coding-stuff/github/clones/java" \
	codinggcp="cd ~/Desktop/coding-stuff/github/clones/pythong" \
	codinggcr="cd ~/Desktop/coding-stuff/github/clones/rust" \
	codinggcw="cd ~/Desktop/coding-stuff/github/clones/web-dev"

# My misc directories.
alias \
    ..="cd .." \
	d="cd ~/Desktop" \
	p="cd ~/Pictures" \
	cf="cd ~/.config" \
    sb="cd ~/.local/bin/" \
    sbs="cd ~/.local/bin/statusbar" \
    sbd="cd ~/.local/bin/dmenu-scripts" \
	mnt="cd /mnt" \
	mntu="cd /mnt/universal-files" \
	mntur="cd /mnt/universal-files/recording-archive"

