# Desktop background and transparency.
#[ -f ~/.fehbg ] && sh ~/.fehbg &
#[ ! -f ~/.fehbg ] && feh --bg-scale //Pictures/desktop-backgrounds/city-night.png
picom -b 

# Restore the last colorscheme and wallpaper that was in use.
wal -R >/dev/null
wall-d -f -r >/dev/null

# Start URxvt dameon for ram useage improvements.
# urxvtd -q -o -f &

# Get numpad working.
numlockx &

# Get clipboard working.
xclip &

# Hide cursor when it isn't needed.
unclutter &

# Setup notifications.
dunst &

# Changes caps to be escape
setxkbmap -option caps:escape

# Load Xresources and redirect xrdb to PyWal's Xresource's file.
#[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/x11/.Xresources ]] && xrdb -merge -I$HOME ${XDG_CONFIG_HOME:-$HOME/.config}/x11/.Xresources && xrdb -merge ${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.Xresources

# Start our display manager
dwmblocks &
exec dwm
