# Desktop background and transparency.
#[ -f ~/.fehbg ] && sh ~/.fehbg &
#[ ! -f ~/.fehbg ] && feh --bg-scale //Pictures/desktop-backgrounds/city-night.png
picom -b

# Restore the last colorscheme and wallpaper that was in use.
wal -Rq -o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" 2>/dev/null
wall-d -f -r 2>/dev/null

# Start URxvt dameon for ram useage improvements.
# urxvtd -q -o -f & 2>/dev/null

# Get numpad working.
numlockx & 2>/dev/null

# Get clipboard working.
xclip & 2>/dev/null

# Hide cursor when it isn't needed.
unclutter & 2>/dev/null

# Setup notifications.
dunst & 2>/dev/null

# Start bluetooth.
blueman-applet & 2>/dev/null

# Start SSH Agent.
#eval "$(ssh-agent -s)" 2>/dev/null 

# Changes caps to be escape
setxkbmap -option caps:escape

# Load Xresources and redirect xrdb to PyWal's Xresource's file.
#[[ -f ${XDG_CONFIG_HOME:-$HOME/.config}/x11/.Xresources ]] && xrdb -merge -I$HOME ${XDG_CONFIG_HOME:-$HOME/.config}/x11/.Xresources && xrdb -merge ${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors.Xresources

# Start our status bar.
dwmblocks &

# Activate dbus variables and start our display manager.
dbus-update-activation-environment --all
ssh-agent dwm
